// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: display.proto

package einkproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Display_GetInfo_FullMethodName           = "/io.gosicp.tableauxeink.v1.Display/GetInfo"
	Display_Refresh_FullMethodName           = "/io.gosicp.tableauxeink.v1.Display/Refresh"
	Display_Fill_FullMethodName              = "/io.gosicp.tableauxeink.v1.Display/Fill"
	Display_SetOverlay_FullMethodName        = "/io.gosicp.tableauxeink.v1.Display/SetOverlay"
	Display_Health_FullMethodName            = "/io.gosicp.tableauxeink.v1.Display/Health"
	Display_Rotate_FullMethodName            = "/io.gosicp.tableauxeink.v1.Display/Rotate"
	Display_ReissueClientCert_FullMethodName = "/io.gosicp.tableauxeink.v1.Display/ReissueClientCert"
	Display_GetMetrics_FullMethodName        = "/io.gosicp.tableauxeink.v1.Display/GetMetrics"
)

// DisplayClient is the client API for Display service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Display drives the Rockchip EBC kernel device wrapped by einklib.
//
// Authentication: every RPC must carry an `authorization: Bearer <token>`
// header in metadata. The token is generated and printed by the server
// at first launch.
//
// Transport: TLS 1.2+ with a server-presented self-signed certificate
// generated and persisted by the server at first launch. Clients can
// either trust the certificate explicitly (--cert flag) or pin its
// SHA-256 fingerprint.
type DisplayClient interface {
	GetInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DisplayInfo, error)
	Refresh(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[RefreshChunk, RefreshResponse], error)
	Fill(ctx context.Context, in *FillRequest, opts ...grpc.CallOption) (*RefreshResponse, error)
	SetOverlay(ctx context.Context, in *SetOverlayRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Health(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthResponse, error)
	Rotate(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*RotateResponse, error)
	ReissueClientCert(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ReissueClientCertResponse, error)
	GetMetrics(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetMetricsResponse, error)
}

type displayClient struct {
	cc grpc.ClientConnInterface
}

func NewDisplayClient(cc grpc.ClientConnInterface) DisplayClient {
	return &displayClient{cc}
}

func (c *displayClient) GetInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DisplayInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisplayInfo)
	err := c.cc.Invoke(ctx, Display_GetInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *displayClient) Refresh(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[RefreshChunk, RefreshResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Display_ServiceDesc.Streams[0], Display_Refresh_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RefreshChunk, RefreshResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Display_RefreshClient = grpc.ClientStreamingClient[RefreshChunk, RefreshResponse]

func (c *displayClient) Fill(ctx context.Context, in *FillRequest, opts ...grpc.CallOption) (*RefreshResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshResponse)
	err := c.cc.Invoke(ctx, Display_Fill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *displayClient) SetOverlay(ctx context.Context, in *SetOverlayRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Display_SetOverlay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *displayClient) Health(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, Display_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *displayClient) Rotate(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*RotateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RotateResponse)
	err := c.cc.Invoke(ctx, Display_Rotate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *displayClient) ReissueClientCert(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ReissueClientCertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReissueClientCertResponse)
	err := c.cc.Invoke(ctx, Display_ReissueClientCert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *displayClient) GetMetrics(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMetricsResponse)
	err := c.cc.Invoke(ctx, Display_GetMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DisplayServer is the server API for Display service.
// All implementations must embed UnimplementedDisplayServer
// for forward compatibility.
//
// Display drives the Rockchip EBC kernel device wrapped by einklib.
//
// Authentication: every RPC must carry an `authorization: Bearer <token>`
// header in metadata. The token is generated and printed by the server
// at first launch.
//
// Transport: TLS 1.2+ with a server-presented self-signed certificate
// generated and persisted by the server at first launch. Clients can
// either trust the certificate explicitly (--cert flag) or pin its
// SHA-256 fingerprint.
type DisplayServer interface {
	GetInfo(context.Context, *emptypb.Empty) (*DisplayInfo, error)
	Refresh(grpc.ClientStreamingServer[RefreshChunk, RefreshResponse]) error
	Fill(context.Context, *FillRequest) (*RefreshResponse, error)
	SetOverlay(context.Context, *SetOverlayRequest) (*emptypb.Empty, error)
	Health(context.Context, *emptypb.Empty) (*HealthResponse, error)
	Rotate(context.Context, *emptypb.Empty) (*RotateResponse, error)
	ReissueClientCert(context.Context, *emptypb.Empty) (*ReissueClientCertResponse, error)
	GetMetrics(context.Context, *emptypb.Empty) (*GetMetricsResponse, error)
	mustEmbedUnimplementedDisplayServer()
}

// UnimplementedDisplayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDisplayServer struct{}

func (UnimplementedDisplayServer) GetInfo(context.Context, *emptypb.Empty) (*DisplayInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInfo not implemented")
}
func (UnimplementedDisplayServer) Refresh(grpc.ClientStreamingServer[RefreshChunk, RefreshResponse]) error {
	return status.Error(codes.Unimplemented, "method Refresh not implemented")
}
func (UnimplementedDisplayServer) Fill(context.Context, *FillRequest) (*RefreshResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Fill not implemented")
}
func (UnimplementedDisplayServer) SetOverlay(context.Context, *SetOverlayRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetOverlay not implemented")
}
func (UnimplementedDisplayServer) Health(context.Context, *emptypb.Empty) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedDisplayServer) Rotate(context.Context, *emptypb.Empty) (*RotateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Rotate not implemented")
}
func (UnimplementedDisplayServer) ReissueClientCert(context.Context, *emptypb.Empty) (*ReissueClientCertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReissueClientCert not implemented")
}
func (UnimplementedDisplayServer) GetMetrics(context.Context, *emptypb.Empty) (*GetMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMetrics not implemented")
}
func (UnimplementedDisplayServer) mustEmbedUnimplementedDisplayServer() {}
func (UnimplementedDisplayServer) testEmbeddedByValue()                 {}

// UnsafeDisplayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DisplayServer will
// result in compilation errors.
type UnsafeDisplayServer interface {
	mustEmbedUnimplementedDisplayServer()
}

func RegisterDisplayServer(s grpc.ServiceRegistrar, srv DisplayServer) {
	// If the following call panics, it indicates UnimplementedDisplayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Display_ServiceDesc, srv)
}

func _Display_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DisplayServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Display_GetInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DisplayServer).GetInfo(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Display_Refresh_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DisplayServer).Refresh(&grpc.GenericServerStream[RefreshChunk, RefreshResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Display_RefreshServer = grpc.ClientStreamingServer[RefreshChunk, RefreshResponse]

func _Display_Fill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DisplayServer).Fill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Display_Fill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DisplayServer).Fill(ctx, req.(*FillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Display_SetOverlay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetOverlayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DisplayServer).SetOverlay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Display_SetOverlay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DisplayServer).SetOverlay(ctx, req.(*SetOverlayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Display_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DisplayServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Display_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DisplayServer).Health(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Display_Rotate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DisplayServer).Rotate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Display_Rotate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DisplayServer).Rotate(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Display_ReissueClientCert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DisplayServer).ReissueClientCert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Display_ReissueClientCert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DisplayServer).ReissueClientCert(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Display_GetMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DisplayServer).GetMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Display_GetMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DisplayServer).GetMetrics(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Display_ServiceDesc is the grpc.ServiceDesc for Display service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Display_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "io.gosicp.tableauxeink.v1.Display",
	HandlerType: (*DisplayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfo",
			Handler:    _Display_GetInfo_Handler,
		},
		{
			MethodName: "Fill",
			Handler:    _Display_Fill_Handler,
		},
		{
			MethodName: "SetOverlay",
			Handler:    _Display_SetOverlay_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _Display_Health_Handler,
		},
		{
			MethodName: "Rotate",
			Handler:    _Display_Rotate_Handler,
		},
		{
			MethodName: "ReissueClientCert",
			Handler:    _Display_ReissueClientCert_Handler,
		},
		{
			MethodName: "GetMetrics",
			Handler:    _Display_GetMetrics_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Refresh",
			Handler:       _Display_Refresh_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "display.proto",
}
