// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: display.proto

package einkproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WaveformMode int32

const (
	WaveformMode_WAVEFORM_MODE_UNSPECIFIED           WaveformMode = 0
	WaveformMode_WAVEFORM_MODE_INIT                  WaveformMode = 1
	WaveformMode_WAVEFORM_MODE_DIRECT_UPDATE         WaveformMode = 2
	WaveformMode_WAVEFORM_MODE_GC16                  WaveformMode = 3
	WaveformMode_WAVEFORM_MODE_GCC16                 WaveformMode = 4
	WaveformMode_WAVEFORM_MODE_ANIMATION             WaveformMode = 5
	WaveformMode_WAVEFORM_MODE_PARTIAL               WaveformMode = 6
	WaveformMode_WAVEFORM_MODE_FULL                  WaveformMode = 7
	WaveformMode_WAVEFORM_MODE_AUTO                  WaveformMode = 8
	WaveformMode_WAVEFORM_MODE_RESET                 WaveformMode = 9
	WaveformMode_WAVEFORM_MODE_BLACK_WHITE           WaveformMode = 10
	WaveformMode_WAVEFORM_MODE_TRANSPARENT           WaveformMode = 11
	WaveformMode_WAVEFORM_MODE_REGAL                 WaveformMode = 12
	WaveformMode_WAVEFORM_MODE_SPECTRA_FULL_GC16     WaveformMode = 13
	WaveformMode_WAVEFORM_MODE_SPECTRA_GLARE_REDUCED WaveformMode = 14
	WaveformMode_WAVEFORM_MODE_SPECTRA_GHOST_REDUCED WaveformMode = 15
	WaveformMode_WAVEFORM_MODE_SPECTRA_FULL_GCC16    WaveformMode = 16
)

// Enum value maps for WaveformMode.
var (
	WaveformMode_name = map[int32]string{
		0:  "WAVEFORM_MODE_UNSPECIFIED",
		1:  "WAVEFORM_MODE_INIT",
		2:  "WAVEFORM_MODE_DIRECT_UPDATE",
		3:  "WAVEFORM_MODE_GC16",
		4:  "WAVEFORM_MODE_GCC16",
		5:  "WAVEFORM_MODE_ANIMATION",
		6:  "WAVEFORM_MODE_PARTIAL",
		7:  "WAVEFORM_MODE_FULL",
		8:  "WAVEFORM_MODE_AUTO",
		9:  "WAVEFORM_MODE_RESET",
		10: "WAVEFORM_MODE_BLACK_WHITE",
		11: "WAVEFORM_MODE_TRANSPARENT",
		12: "WAVEFORM_MODE_REGAL",
		13: "WAVEFORM_MODE_SPECTRA_FULL_GC16",
		14: "WAVEFORM_MODE_SPECTRA_GLARE_REDUCED",
		15: "WAVEFORM_MODE_SPECTRA_GHOST_REDUCED",
		16: "WAVEFORM_MODE_SPECTRA_FULL_GCC16",
	}
	WaveformMode_value = map[string]int32{
		"WAVEFORM_MODE_UNSPECIFIED":           0,
		"WAVEFORM_MODE_INIT":                  1,
		"WAVEFORM_MODE_DIRECT_UPDATE":         2,
		"WAVEFORM_MODE_GC16":                  3,
		"WAVEFORM_MODE_GCC16":                 4,
		"WAVEFORM_MODE_ANIMATION":             5,
		"WAVEFORM_MODE_PARTIAL":               6,
		"WAVEFORM_MODE_FULL":                  7,
		"WAVEFORM_MODE_AUTO":                  8,
		"WAVEFORM_MODE_RESET":                 9,
		"WAVEFORM_MODE_BLACK_WHITE":           10,
		"WAVEFORM_MODE_TRANSPARENT":           11,
		"WAVEFORM_MODE_REGAL":                 12,
		"WAVEFORM_MODE_SPECTRA_FULL_GC16":     13,
		"WAVEFORM_MODE_SPECTRA_GLARE_REDUCED": 14,
		"WAVEFORM_MODE_SPECTRA_GHOST_REDUCED": 15,
		"WAVEFORM_MODE_SPECTRA_FULL_GCC16":    16,
	}
)

func (x WaveformMode) Enum() *WaveformMode {
	p := new(WaveformMode)
	*p = x
	return p
}

func (x WaveformMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WaveformMode) Descriptor() protoreflect.EnumDescriptor {
	return file_display_proto_enumTypes[0].Descriptor()
}

func (WaveformMode) Type() protoreflect.EnumType {
	return &file_display_proto_enumTypes[0]
}

func (x WaveformMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WaveformMode.Descriptor instead.
func (WaveformMode) EnumDescriptor() ([]byte, []int) {
	return file_display_proto_rawDescGZIP(), []int{0}
}

type DisplayInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         int32                  `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	VirtualWidth  int32                  `protobuf:"varint,3,opt,name=virtual_width,json=virtualWidth,proto3" json:"virtual_width,omitempty"`
	VirtualHeight int32                  `protobuf:"varint,4,opt,name=virtual_height,json=virtualHeight,proto3" json:"virtual_height,omitempty"`
	Color         bool                   `protobuf:"varint,5,opt,name=color,proto3" json:"color,omitempty"`
	AppVersion    string                 `protobuf:"bytes,6,opt,name=app_version,json=appVersion,proto3" json:"app_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisplayInfo) Reset() {
	*x = DisplayInfo{}
	mi := &file_display_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisplayInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisplayInfo) ProtoMessage() {}

func (x *DisplayInfo) ProtoReflect() protoreflect.Message {
	mi := &file_display_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisplayInfo.ProtoReflect.Descriptor instead.
func (*DisplayInfo) Descriptor() ([]byte, []int) {
	return file_display_proto_rawDescGZIP(), []int{0}
}

func (x *DisplayInfo) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *DisplayInfo) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *DisplayInfo) GetVirtualWidth() int32 {
	if x != nil {
		return x.VirtualWidth
	}
	return 0
}

func (x *DisplayInfo) GetVirtualHeight() int32 {
	if x != nil {
		return x.VirtualHeight
	}
	return 0
}

func (x *DisplayInfo) GetColor() bool {
	if x != nil {
		return x.Color
	}
	return false
}

func (x *DisplayInfo) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

type Region struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X1            int32                  `protobuf:"varint,1,opt,name=x1,proto3" json:"x1,omitempty"`
	Y1            int32                  `protobuf:"varint,2,opt,name=y1,proto3" json:"y1,omitempty"`
	X2            int32                  `protobuf:"varint,3,opt,name=x2,proto3" json:"x2,omitempty"`
	Y2            int32                  `protobuf:"varint,4,opt,name=y2,proto3" json:"y2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Region) Reset() {
	*x = Region{}
	mi := &file_display_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Region) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Region) ProtoMessage() {}

func (x *Region) ProtoReflect() protoreflect.Message {
	mi := &file_display_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Region.ProtoReflect.Descriptor instead.
func (*Region) Descriptor() ([]byte, []int) {
	return file_display_proto_rawDescGZIP(), []int{1}
}

func (x *Region) GetX1() int32 {
	if x != nil {
		return x.X1
	}
	return 0
}

func (x *Region) GetY1() int32 {
	if x != nil {
		return x.Y1
	}
	return 0
}

func (x *Region) GetX2() int32 {
	if x != nil {
		return x.X2
	}
	return 0
}

func (x *Region) GetY2() int32 {
	if x != nil {
		return x.Y2
	}
	return 0
}

type RefreshHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          WaveformMode           `protobuf:"varint,1,opt,name=mode,proto3,enum=io.gosicp.tableauxeink.v1.WaveformMode" json:"mode,omitempty"`
	Region        *Region                `protobuf:"bytes,2,opt,name=region,proto3,oneof" json:"region,omitempty"`
	TotalBytes    int64                  `protobuf:"varint,3,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshHeader) Reset() {
	*x = RefreshHeader{}
	mi := &file_display_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshHeader) ProtoMessage() {}

func (x *RefreshHeader) ProtoReflect() protoreflect.Message {
	mi := &file_display_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshHeader.ProtoReflect.Descriptor instead.
func (*RefreshHeader) Descriptor() ([]byte, []int) {
	return file_display_proto_rawDescGZIP(), []int{2}
}

func (x *RefreshHeader) GetMode() WaveformMode {
	if x != nil {
		return x.Mode
	}
	return WaveformMode_WAVEFORM_MODE_UNSPECIFIED
}

func (x *RefreshHeader) GetRegion() *Region {
	if x != nil {
		return x.Region
	}
	return nil
}

func (x *RefreshHeader) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

type RefreshChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*RefreshChunk_Header
	//	*RefreshChunk_Data
	Payload       isRefreshChunk_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshChunk) Reset() {
	*x = RefreshChunk{}
	mi := &file_display_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshChunk) ProtoMessage() {}

func (x *RefreshChunk) ProtoReflect() protoreflect.Message {
	mi := &file_display_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshChunk.ProtoReflect.Descriptor instead.
func (*RefreshChunk) Descriptor() ([]byte, []int) {
	return file_display_proto_rawDescGZIP(), []int{3}
}

func (x *RefreshChunk) GetPayload() isRefreshChunk_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RefreshChunk) GetHeader() *RefreshHeader {
	if x != nil {
		if x, ok := x.Payload.(*RefreshChunk_Header); ok {
			return x.Header
		}
	}
	return nil
}

func (x *RefreshChunk) GetData() []byte {
	if x != nil {
		if x, ok := x.Payload.(*RefreshChunk_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isRefreshChunk_Payload interface {
	isRefreshChunk_Payload()
}

type RefreshChunk_Header struct {
	Header *RefreshHeader `protobuf:"bytes,1,opt,name=header,proto3,oneof"`
}

type RefreshChunk_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*RefreshChunk_Header) isRefreshChunk_Payload() {}

func (*RefreshChunk_Data) isRefreshChunk_Payload() {}

type RefreshResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ElapsedMs     int64                  `protobuf:"varint,1,opt,name=elapsed_ms,json=elapsedMs,proto3" json:"elapsed_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshResponse) Reset() {
	*x = RefreshResponse{}
	mi := &file_display_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshResponse) ProtoMessage() {}

func (x *RefreshResponse) ProtoReflect() protoreflect.Message {
	mi := &file_display_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshResponse.ProtoReflect.Descriptor instead.
func (*RefreshResponse) Descriptor() ([]byte, []int) {
	return file_display_proto_rawDescGZIP(), []int{4}
}

func (x *RefreshResponse) GetElapsedMs() int64 {
	if x != nil {
		return x.ElapsedMs
	}
	return 0
}

type FillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Argb          uint32                 `protobuf:"varint,1,opt,name=argb,proto3" json:"argb,omitempty"`
	Mode          WaveformMode           `protobuf:"varint,2,opt,name=mode,proto3,enum=io.gosicp.tableauxeink.v1.WaveformMode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FillRequest) Reset() {
	*x = FillRequest{}
	mi := &file_display_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FillRequest) ProtoMessage() {}

func (x *FillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_display_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FillRequest.ProtoReflect.Descriptor instead.
func (*FillRequest) Descriptor() ([]byte, []int) {
	return file_display_proto_rawDescGZIP(), []int{5}
}

func (x *FillRequest) GetArgb() uint32 {
	if x != nil {
		return x.Argb
	}
	return 0
}

func (x *FillRequest) GetMode() WaveformMode {
	if x != nil {
		return x.Mode
	}
	return WaveformMode_WAVEFORM_MODE_UNSPECIFIED
}

type SetOverlayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetOverlayRequest) Reset() {
	*x = SetOverlayRequest{}
	mi := &file_display_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetOverlayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetOverlayRequest) ProtoMessage() {}

func (x *SetOverlayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_display_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetOverlayRequest.ProtoReflect.Descriptor instead.
func (*SetOverlayRequest) Descriptor() ([]byte, []int) {
	return file_display_proto_rawDescGZIP(), []int{6}
}

func (x *SetOverlayRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceOpen    bool                   `protobuf:"varint,1,opt,name=device_open,json=deviceOpen,proto3" json:"device_open,omitempty"`
	LastError     string                 `protobuf:"bytes,2,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	ServerVersion string                 `protobuf:"bytes,3,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,4,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_display_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_display_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_display_proto_rawDescGZIP(), []int{7}
}

func (x *HealthResponse) GetDeviceOpen() bool {
	if x != nil {
		return x.DeviceOpen
	}
	return false
}

func (x *HealthResponse) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *HealthResponse) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

func (x *HealthResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

type RotateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScheduledAtMs int64                  `protobuf:"varint,1,opt,name=scheduled_at_ms,json=scheduledAtMs,proto3" json:"scheduled_at_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateResponse) Reset() {
	*x = RotateResponse{}
	mi := &file_display_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateResponse) ProtoMessage() {}

func (x *RotateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_display_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateResponse.ProtoReflect.Descriptor instead.
func (*RotateResponse) Descriptor() ([]byte, []int) {
	return file_display_proto_rawDescGZIP(), []int{8}
}

func (x *RotateResponse) GetScheduledAtMs() int64 {
	if x != nil {
		return x.ScheduledAtMs
	}
	return 0
}

type GetMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PromText      string                 `protobuf:"bytes,1,opt,name=prom_text,json=promText,proto3" json:"prom_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricsResponse) Reset() {
	*x = GetMetricsResponse{}
	mi := &file_display_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsResponse) ProtoMessage() {}

func (x *GetMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_display_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetMetricsResponse) Descriptor() ([]byte, []int) {
	return file_display_proto_rawDescGZIP(), []int{9}
}

func (x *GetMetricsResponse) GetPromText() string {
	if x != nil {
		return x.PromText
	}
	return ""
}

type ReissueClientCertResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ClientCertPem         string                 `protobuf:"bytes,1,opt,name=client_cert_pem,json=clientCertPem,proto3" json:"client_cert_pem,omitempty"`
	ClientKeyPem          string                 `protobuf:"bytes,2,opt,name=client_key_pem,json=clientKeyPem,proto3" json:"client_key_pem,omitempty"`
	ClientCertFingerprint string                 `protobuf:"bytes,3,opt,name=client_cert_fingerprint,json=clientCertFingerprint,proto3" json:"client_cert_fingerprint,omitempty"`
	ServerRestartInMs     int64                  `protobuf:"varint,4,opt,name=server_restart_in_ms,json=serverRestartInMs,proto3" json:"server_restart_in_ms,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ReissueClientCertResponse) Reset() {
	*x = ReissueClientCertResponse{}
	mi := &file_display_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReissueClientCertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReissueClientCertResponse) ProtoMessage() {}

func (x *ReissueClientCertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_display_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReissueClientCertResponse.ProtoReflect.Descriptor instead.
func (*ReissueClientCertResponse) Descriptor() ([]byte, []int) {
	return file_display_proto_rawDescGZIP(), []int{10}
}

func (x *ReissueClientCertResponse) GetClientCertPem() string {
	if x != nil {
		return x.ClientCertPem
	}
	return ""
}

func (x *ReissueClientCertResponse) GetClientKeyPem() string {
	if x != nil {
		return x.ClientKeyPem
	}
	return ""
}

func (x *ReissueClientCertResponse) GetClientCertFingerprint() string {
	if x != nil {
		return x.ClientCertFingerprint
	}
	return ""
}

func (x *ReissueClientCertResponse) GetServerRestartInMs() int64 {
	if x != nil {
		return x.ServerRestartInMs
	}
	return 0
}

var File_display_proto protoreflect.FileDescriptor

const file_display_proto_rawDesc = "" +
	"\n" +
	"\rdisplay.proto\x12\x19io.gosicp.tableauxeink.v1\x1a\x1bgoogle/protobuf/empty.proto\"\xbe\x01\n" +
	"\vDisplayInfo\x12\x14\n" +
	"\x05width\x18\x01 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x05R\x06height\x12#\n" +
	"\rvirtual_width\x18\x03 \x01(\x05R\fvirtualWidth\x12%\n" +
	"\x0evirtual_height\x18\x04 \x01(\x05R\rvirtualHeight\x12\x14\n" +
	"\x05color\x18\x05 \x01(\bR\x05color\x12\x1f\n" +
	"\vapp_version\x18\x06 \x01(\tR\n" +
	"appVersion\"H\n" +
	"\x06Region\x12\x0e\n" +
	"\x02x1\x18\x01 \x01(\x05R\x02x1\x12\x0e\n" +
	"\x02y1\x18\x02 \x01(\x05R\x02y1\x12\x0e\n" +
	"\x02x2\x18\x03 \x01(\x05R\x02x2\x12\x0e\n" +
	"\x02y2\x18\x04 \x01(\x05R\x02y2\"\xb8\x01\n" +
	"\rRefreshHeader\x12;\n" +
	"\x04mode\x18\x01 \x01(\x0e2'.io.gosicp.tableauxeink.v1.WaveformModeR\x04mode\x12>\n" +
	"\x06region\x18\x02 \x01(\v2!.io.gosicp.tableauxeink.v1.RegionH\x00R\x06region\x88\x01\x01\x12\x1f\n" +
	"\vtotal_bytes\x18\x03 \x01(\x03R\n" +
	"totalBytesB\t\n" +
	"\a_region\"s\n" +
	"\fRefreshChunk\x12B\n" +
	"\x06header\x18\x01 \x01(\v2(.io.gosicp.tableauxeink.v1.RefreshHeaderH\x00R\x06header\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\t\n" +
	"\apayload\"0\n" +
	"\x0fRefreshResponse\x12\x1d\n" +
	"\n" +
	"elapsed_ms\x18\x01 \x01(\x03R\telapsedMs\"^\n" +
	"\vFillRequest\x12\x12\n" +
	"\x04argb\x18\x01 \x01(\rR\x04argb\x12;\n" +
	"\x04mode\x18\x02 \x01(\x0e2'.io.gosicp.tableauxeink.v1.WaveformModeR\x04mode\"-\n" +
	"\x11SetOverlayRequest\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\"\x9e\x01\n" +
	"\x0eHealthResponse\x12\x1f\n" +
	"\vdevice_open\x18\x01 \x01(\bR\n" +
	"deviceOpen\x12\x1d\n" +
	"\n" +
	"last_error\x18\x02 \x01(\tR\tlastError\x12%\n" +
	"\x0eserver_version\x18\x03 \x01(\tR\rserverVersion\x12%\n" +
	"\x0euptime_seconds\x18\x04 \x01(\x03R\ruptimeSeconds\"8\n" +
	"\x0eRotateResponse\x12&\n" +
	"\x0fscheduled_at_ms\x18\x01 \x01(\x03R\rscheduledAtMs\"1\n" +
	"\x12GetMetricsResponse\x12\x1b\n" +
	"\tprom_text\x18\x01 \x01(\tR\bpromText\"\xd2\x01\n" +
	"\x19ReissueClientCertResponse\x12&\n" +
	"\x0fclient_cert_pem\x18\x01 \x01(\tR\rclientCertPem\x12$\n" +
	"\x0eclient_key_pem\x18\x02 \x01(\tR\fclientKeyPem\x126\n" +
	"\x17client_cert_fingerprint\x18\x03 \x01(\tR\x15clientCertFingerprint\x12/\n" +
	"\x14server_restart_in_ms\x18\x04 \x01(\x03R\x11serverRestartInMs*\x8c\x04\n" +
	"\fWaveformMode\x12\x1d\n" +
	"\x19WAVEFORM_MODE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12WAVEFORM_MODE_INIT\x10\x01\x12\x1f\n" +
	"\x1bWAVEFORM_MODE_DIRECT_UPDATE\x10\x02\x12\x16\n" +
	"\x12WAVEFORM_MODE_GC16\x10\x03\x12\x17\n" +
	"\x13WAVEFORM_MODE_GCC16\x10\x04\x12\x1b\n" +
	"\x17WAVEFORM_MODE_ANIMATION\x10\x05\x12\x19\n" +
	"\x15WAVEFORM_MODE_PARTIAL\x10\x06\x12\x16\n" +
	"\x12WAVEFORM_MODE_FULL\x10\a\x12\x16\n" +
	"\x12WAVEFORM_MODE_AUTO\x10\b\x12\x17\n" +
	"\x13WAVEFORM_MODE_RESET\x10\t\x12\x1d\n" +
	"\x19WAVEFORM_MODE_BLACK_WHITE\x10\n" +
	"\x12\x1d\n" +
	"\x19WAVEFORM_MODE_TRANSPARENT\x10\v\x12\x17\n" +
	"\x13WAVEFORM_MODE_REGAL\x10\f\x12#\n" +
	"\x1fWAVEFORM_MODE_SPECTRA_FULL_GC16\x10\r\x12'\n" +
	"#WAVEFORM_MODE_SPECTRA_GLARE_REDUCED\x10\x0e\x12'\n" +
	"#WAVEFORM_MODE_SPECTRA_GHOST_REDUCED\x10\x0f\x12$\n" +
	" WAVEFORM_MODE_SPECTRA_FULL_GCC16\x10\x102\xb8\x05\n" +
	"\aDisplay\x12I\n" +
	"\aGetInfo\x12\x16.google.protobuf.Empty\x1a&.io.gosicp.tableauxeink.v1.DisplayInfo\x12`\n" +
	"\aRefresh\x12'.io.gosicp.tableauxeink.v1.RefreshChunk\x1a*.io.gosicp.tableauxeink.v1.RefreshResponse(\x01\x12Z\n" +
	"\x04Fill\x12&.io.gosicp.tableauxeink.v1.FillRequest\x1a*.io.gosicp.tableauxeink.v1.RefreshResponse\x12R\n" +
	"\n" +
	"SetOverlay\x12,.io.gosicp.tableauxeink.v1.SetOverlayRequest\x1a\x16.google.protobuf.Empty\x12K\n" +
	"\x06Health\x12\x16.google.protobuf.Empty\x1a).io.gosicp.tableauxeink.v1.HealthResponse\x12K\n" +
	"\x06Rotate\x12\x16.google.protobuf.Empty\x1a).io.gosicp.tableauxeink.v1.RotateResponse\x12a\n" +
	"\x11ReissueClientCert\x12\x16.google.protobuf.Empty\x1a4.io.gosicp.tableauxeink.v1.ReissueClientCertResponse\x12S\n" +
	"\n" +
	"GetMetrics\x12\x16.google.protobuf.Empty\x1a-.io.gosicp.tableauxeink.v1.GetMetricsResponseB9Z7github.com/go-sicp/tableaux-eink-go/einkproto;einkprotob\x06proto3"

var (
	file_display_proto_rawDescOnce sync.Once
	file_display_proto_rawDescData []byte
)

func file_display_proto_rawDescGZIP() []byte {
	file_display_proto_rawDescOnce.Do(func() {
		file_display_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_display_proto_rawDesc), len(file_display_proto_rawDesc)))
	})
	return file_display_proto_rawDescData
}

var file_display_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_display_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_display_proto_goTypes = []any{
	(WaveformMode)(0),                 // 0: io.gosicp.tableauxeink.v1.WaveformMode
	(*DisplayInfo)(nil),               // 1: io.gosicp.tableauxeink.v1.DisplayInfo
	(*Region)(nil),                    // 2: io.gosicp.tableauxeink.v1.Region
	(*RefreshHeader)(nil),             // 3: io.gosicp.tableauxeink.v1.RefreshHeader
	(*RefreshChunk)(nil),              // 4: io.gosicp.tableauxeink.v1.RefreshChunk
	(*RefreshResponse)(nil),           // 5: io.gosicp.tableauxeink.v1.RefreshResponse
	(*FillRequest)(nil),               // 6: io.gosicp.tableauxeink.v1.FillRequest
	(*SetOverlayRequest)(nil),         // 7: io.gosicp.tableauxeink.v1.SetOverlayRequest
	(*HealthResponse)(nil),            // 8: io.gosicp.tableauxeink.v1.HealthResponse
	(*RotateResponse)(nil),            // 9: io.gosicp.tableauxeink.v1.RotateResponse
	(*GetMetricsResponse)(nil),        // 10: io.gosicp.tableauxeink.v1.GetMetricsResponse
	(*ReissueClientCertResponse)(nil), // 11: io.gosicp.tableauxeink.v1.ReissueClientCertResponse
	(*emptypb.Empty)(nil),             // 12: google.protobuf.Empty
}
var file_display_proto_depIdxs = []int32{
	0,  // 0: io.gosicp.tableauxeink.v1.RefreshHeader.mode:type_name -> io.gosicp.tableauxeink.v1.WaveformMode
	2,  // 1: io.gosicp.tableauxeink.v1.RefreshHeader.region:type_name -> io.gosicp.tableauxeink.v1.Region
	3,  // 2: io.gosicp.tableauxeink.v1.RefreshChunk.header:type_name -> io.gosicp.tableauxeink.v1.RefreshHeader
	0,  // 3: io.gosicp.tableauxeink.v1.FillRequest.mode:type_name -> io.gosicp.tableauxeink.v1.WaveformMode
	12, // 4: io.gosicp.tableauxeink.v1.Display.GetInfo:input_type -> google.protobuf.Empty
	4,  // 5: io.gosicp.tableauxeink.v1.Display.Refresh:input_type -> io.gosicp.tableauxeink.v1.RefreshChunk
	6,  // 6: io.gosicp.tableauxeink.v1.Display.Fill:input_type -> io.gosicp.tableauxeink.v1.FillRequest
	7,  // 7: io.gosicp.tableauxeink.v1.Display.SetOverlay:input_type -> io.gosicp.tableauxeink.v1.SetOverlayRequest
	12, // 8: io.gosicp.tableauxeink.v1.Display.Health:input_type -> google.protobuf.Empty
	12, // 9: io.gosicp.tableauxeink.v1.Display.Rotate:input_type -> google.protobuf.Empty
	12, // 10: io.gosicp.tableauxeink.v1.Display.ReissueClientCert:input_type -> google.protobuf.Empty
	12, // 11: io.gosicp.tableauxeink.v1.Display.GetMetrics:input_type -> google.protobuf.Empty
	1,  // 12: io.gosicp.tableauxeink.v1.Display.GetInfo:output_type -> io.gosicp.tableauxeink.v1.DisplayInfo
	5,  // 13: io.gosicp.tableauxeink.v1.Display.Refresh:output_type -> io.gosicp.tableauxeink.v1.RefreshResponse
	5,  // 14: io.gosicp.tableauxeink.v1.Display.Fill:output_type -> io.gosicp.tableauxeink.v1.RefreshResponse
	12, // 15: io.gosicp.tableauxeink.v1.Display.SetOverlay:output_type -> google.protobuf.Empty
	8,  // 16: io.gosicp.tableauxeink.v1.Display.Health:output_type -> io.gosicp.tableauxeink.v1.HealthResponse
	9,  // 17: io.gosicp.tableauxeink.v1.Display.Rotate:output_type -> io.gosicp.tableauxeink.v1.RotateResponse
	11, // 18: io.gosicp.tableauxeink.v1.Display.ReissueClientCert:output_type -> io.gosicp.tableauxeink.v1.ReissueClientCertResponse
	10, // 19: io.gosicp.tableauxeink.v1.Display.GetMetrics:output_type -> io.gosicp.tableauxeink.v1.GetMetricsResponse
	12, // [12:20] is the sub-list for method output_type
	4,  // [4:12] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_display_proto_init() }
func file_display_proto_init() {
	if File_display_proto != nil {
		return
	}
	file_display_proto_msgTypes[2].OneofWrappers = []any{}
	file_display_proto_msgTypes[3].OneofWrappers = []any{
		(*RefreshChunk_Header)(nil),
		(*RefreshChunk_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_display_proto_rawDesc), len(file_display_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_display_proto_goTypes,
		DependencyIndexes: file_display_proto_depIdxs,
		EnumInfos:         file_display_proto_enumTypes,
		MessageInfos:      file_display_proto_msgTypes,
	}.Build()
	File_display_proto = out.File
	file_display_proto_goTypes = nil
	file_display_proto_depIdxs = nil
}
